### ISSUE TITLE
客户端连接不上

### ISSUE THREAD

**Issue by nickleefly** [boris1993/shadowsocks-v2ray-docker#3]
配置如下
1, Cloudflare 添加 A 记录 www.mydomain.top 指向 vps IP
先是DNS only 跑起来 Caddy container, 然后改成 DNS and http proxy

2, Caddyfile
```
www.mydomain.top {
  tls email@gmail.com
  log /var/log/caddy.log
  proxy /shadowsocks localhost:10001 {
    without /shadowsocks
    websocket
    header_upstream -Origin
  }
}
```

运行Caddy
```docker run -d -v $(pwd)/Caddyfile:/etc/Caddyfile --env ACME_AGREE=true -p 80:80 -p 443:443 --name caddy abiosoft/caddy```

3, docker-compose
docker-compose.yaml
```
version: '3'

services:
  shadowsocks-v2ray-docker:
    image: boris1993/shadowsocks-v2ray-docker:v3.2.5-1.1.0
    restart: always
    ports:
      - 127.0.0.1:10001:1080
    environment:
      PASSWORD: "ASecurePassword"
      HOST: "www.mydomain.top"
```

`docker-compose up -d`

4, 客户端连接失败
